[database]
addrs= "localhost:27018"
user= "iris"
passwd= "irispassword"
database= "rainbow-server"

[server]
node_urls="tcp://192.168.150.41:26657"
worker_num_create_task=1
worker_num_execute_task=30
worker_max_sleep_time=120
block_num_per_worker_handle=100
max_connection_num=100
init_connection_num=5
bech32_acc_prefix=""
chain_id=""
chain_block_interval=5
behind_block_num=0
promethous_port=9090
support_modules=""
deny_modules=""